// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServiceFlow.Infrastructure.Persistence;

#nullable disable

namespace ServiceFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("serviceflow")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServiceFlow.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("ix_customers_phone_number");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_user_id")
                        .HasFilter("user_id IS NOT NULL");

                    b.ToTable("customers", "serviceflow");
                });

            modelBuilder.Entity("ServiceFlow.Domain.RepairRequests.RepairMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("media_type");

                    b.Property<string>("MimeType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mime_type");

                    b.Property<Guid>("RepairRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("repair_request_id");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_path");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.HasKey("Id")
                        .HasName("pk_repair_media");

                    b.HasIndex("RepairRequestId")
                        .HasDatabaseName("ix_repair_media_repair_request_id");

                    b.ToTable("repair_media", "serviceflow");
                });

            modelBuilder.Entity("ServiceFlow.Domain.RepairRequests.RepairRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("CustomerDecision")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("customer_decision");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("decision_note");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("issue_description");

                    b.Property<long>("PriceEstimateCents")
                        .HasColumnType("bigint")
                        .HasColumnName("price_estimate_cents");

                    b.Property<Guid>("ServiceOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_order_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("urgency");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_repair_requests");

                    b.HasIndex("CustomerDecision")
                        .HasDatabaseName("ix_repair_requests_customer_decision");

                    b.HasIndex("ServiceOrderId")
                        .HasDatabaseName("ix_repair_requests_service_order_id");

                    b.ToTable("repair_requests", "serviceflow");
                });

            modelBuilder.Entity("ServiceFlow.Domain.ServiceOrders.ServiceOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedStaffId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_staff_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("OpeningDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("opening_description");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("stage");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_service_orders");

                    b.HasIndex("AssignedStaffId")
                        .HasDatabaseName("ix_service_orders_assigned_staff_id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_service_orders_created_at");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_service_orders_customer_id");

                    b.HasIndex("Stage")
                        .HasDatabaseName("ix_service_orders_stage");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_service_orders_vehicle_id");

                    b.ToTable("service_orders", "serviceflow");
                });

            modelBuilder.Entity("ServiceFlow.Domain.ServiceOrders.ServiceStatusHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<Guid>("ChangedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by_user_id");

                    b.Property<string>("FromStage")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("from_stage");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<Guid>("ServiceOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_order_id");

                    b.Property<string>("ToStage")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("to_stage");

                    b.HasKey("Id")
                        .HasName("pk_service_status_history");

                    b.HasIndex("ServiceOrderId", "ChangedAt")
                        .HasDatabaseName("ix_service_status_history_service_order_id_changed_at");

                    b.ToTable("service_status_history", "serviceflow");
                });

            modelBuilder.Entity("ServiceFlow.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "serviceflow");
                });

            modelBuilder.Entity("ServiceFlow.Domain.Vehicles.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("license_plate");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("model");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Vin")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("vin");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_vehicles_customer_id");

                    b.HasIndex("LicensePlate")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicles_license_plate");

                    b.ToTable("vehicles", "serviceflow");
                });

            modelBuilder.Entity("ServiceFlow.Domain.RepairRequests.RepairMedia", b =>
                {
                    b.HasOne("ServiceFlow.Domain.RepairRequests.RepairRequest", null)
                        .WithMany("Media")
                        .HasForeignKey("RepairRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_repair_media_repair_requests_repair_request_id");
                });

            modelBuilder.Entity("ServiceFlow.Domain.RepairRequests.RepairRequest", b =>
                {
                    b.HasOne("ServiceFlow.Domain.ServiceOrders.ServiceOrder", null)
                        .WithMany("RepairRequests")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_repair_requests_service_orders_service_order_id");
                });

            modelBuilder.Entity("ServiceFlow.Domain.ServiceOrders.ServiceStatusHistoryEntry", b =>
                {
                    b.HasOne("ServiceFlow.Domain.ServiceOrders.ServiceOrder", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("ServiceOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_service_status_history_service_orders_service_order_id");
                });

            modelBuilder.Entity("ServiceFlow.Domain.Vehicles.Vehicle", b =>
                {
                    b.HasOne("ServiceFlow.Domain.Customers.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ServiceFlow.Domain.Customers.Customer", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("ServiceFlow.Domain.RepairRequests.RepairRequest", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("ServiceFlow.Domain.ServiceOrders.ServiceOrder", b =>
                {
                    b.Navigation("RepairRequests");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
